"""Project the day brief for day N out of the master plan (plan §24, §7–§23).

Run as `./m brief N`. Prints, for one day: the §24.2 row that defines it, the full definition
of every ID it must close, its phase and that phase's gate, the days either side of it, and
where the ledger says we are. It ends with the commands that fetch the judgement-bearing
sections of the plan — the depth contract, the style guide, the principles, the silent
failures — which are deliberately *not* projected. Those are read in full or not at all.

**Every line of the output is copied verbatim from a source file.** Nothing here summarises,
paraphrases or generates: a brief that invented an ID description would be Principle 8's
failure mode wearing a helpful face. The only lines this script writes itself are its own
header, the table of `sed` commands at the end, and the one loud row that fires when the plan
names an ID no curriculum table defines. None of them states a fact about the curriculum.
`tests/test_brief.py` asserts exactly that, over every shape of day the plan contains.

Exit code 0 = brief written, 1 = the plan has no row for that day.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# A Windows console defaults to cp1252, and neither the ledger's vocabulary nor the plan's
# day titles fit in it. The shell every day document is written for is Git Bash (CLAUDE.md),
# so decode failures must never be what a learner sees instead of a check result.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
PLAN = ROOT / "docs/00_MASTER_PLAN.md"
PROGRESS = ROOT / "docs/PROGRESS.md"

#: Where the judgement-bearing sections live. Projecting these would mean compressing them,
#: and compressing them is compressing the days (plan §25, §28). They are listed, not copied.
FULL_TEXT_ON_DEMAND: tuple[tuple[str, str], ...] = (
    ("The depth contract — read before writing any day", "'/^## 25 /,/^## 26 /p'"),
    ("The five silent failures", "'/^## 6 /,/^## 7 /p'"),
    ("The core principles", "'/^## 2 /,/^## 3 /p'"),
    ("The style guide", "'/^## 28 /,/^## 29 /p'"),
)


def cells(line: str) -> list[str]:
    """Split one markdown table row into its trimmed cells."""
    return [c.strip() for c in line.strip().strip("|").split("|")]


def parse_plan(day: int) -> tuple[list[str], list[str] | None, list[str], dict[str, list[str]]]:
    """Return (day row, phase row, neighbour rows, ID definitions) for `day`, all verbatim.

    One pass over the plan. The three table shapes are told apart by their columns, not by
    which section they are in, so a section being reordered cannot silently break this.
    """
    day_row: list[str] | None = None
    phase_row: list[str] | None = None
    neighbours: list[str] = []
    id_defs: dict[str, list[str]] = {}

    for line in PLAN.read_text(encoding="utf-8").split("\n"):
        if not line.startswith("|"):
            continue
        c = cells(line)
        # §24.2, `day | title | IDs closed`.
        if len(c) == 3 and c[0].isdigit():
            if int(c[0]) == day:
                day_row = c
            elif abs(int(c[0]) - day) == 1:
                neighbours.append(f"| {c[0]} | {c[1]} | {c[2]} |")
        # §24.1, `phase | days | theme | gate`. The day range is what identifies it.
        if len(c) == 4 and c[0].isdigit() and re.fullmatch(r"\d+[\u2013-]\d+", c[1]):
            low, high = (int(x) for x in re.split(r"[\u2013-]", c[1]))
            if low <= day <= high:
                phase_row = c
        # §7–§23, `` `ID` | concept | closes on ``.
        if len(c) == 3 and c[0].startswith("`") and c[2].isdigit():
            id_defs[c[0].strip("`")] = c

    if day_row is None:
        raise SystemExit(f"brief: the plan's §24.2 has no row for day {day}")
    return day_row, phase_row, neighbours, id_defs


def ledger_row() -> str:
    """The last row of PROGRESS.md, verbatim — or the honest absence of one."""
    rows = [
        line
        for line in PROGRESS.read_text(encoding="utf-8").split("\n")
        if re.match(r"^\|\s*\d+\s*\|", line)
    ]
    if not rows:
        return "_No rows in `docs/PROGRESS.md` — no day is recorded complete (plan §27)._"
    return rows[-1]


def build(day: int) -> str:
    """Assemble the brief for `day`."""
    day_row, phase_row, neighbours, id_defs = parse_plan(day)
    ids = [i.strip(" `") for i in day_row[2].split(",") if i.strip(" `\u2014-")]

    out: list[str] = [
        f"# Day {day} brief",
        "",
        "**Generated by `./m brief` — do not edit, and do not cite this file.** Every row below is",
        "copied verbatim from `docs/00_MASTER_PLAN.md` or `docs/PROGRESS.md`; cite those. This brief",
        "replaces *reading the whole plan*, not reading the sections listed at the end.",
        "",
        "## The day (§24.2, verbatim)",
        "",
        "| Day | Title | IDs closed |",
        "| --- | --- | --- |",
        f"| {day_row[0]} | {day_row[1]} | {day_row[2]} |",
        "",
    ]

    if ids:
        out += [
            "## Close exactly these IDs — no more, no fewer (§7–§23, verbatim)",
            "",
            "| ID | Concept | Closes on |",
            "| --- | --- | --- |",
        ]
        for i in ids:
            row = id_defs.get(i)
            if row is None:
                # The §24.2 row names an ID no curriculum table defines: the plan disagrees with
                # itself. Say that, loudly, rather than inventing the definition it is missing.
                out.append(
                    f"| `{i}` | **NO DEFINITION IN §7–§23 — THE PLAN DISAGREES WITH ITSELF** | ? |"
                )
            else:
                out.append(f"| {row[0]} | {row[1]} | {row[2]} |")
    else:
        # Prose, not a table row: every row of every table in this file is copied from a source,
        # and a row saying "there is nothing here" would be the one exception. There isn't one.
        out += [
            "## Curriculum IDs",
            "",
            "_The §24.2 row above assigns this day no curriculum IDs._",
        ]

    if phase_row is not None:
        out += [
            "",
            "## The phase this day sits in, and its gate (§24.1, verbatim)",
            "",
            "| Phase | Days | Theme | Gate |",
            "| --- | --- | --- | --- |",
            f"| {phase_row[0]} | {phase_row[1]} | {phase_row[2]} | {phase_row[3]} |",
        ]

    if neighbours:
        out += [
            "",
            "## Either side of it (§24.2, verbatim)",
            "",
            "| Day | Title | IDs closed |",
            "| --- | --- | --- |",
            *neighbours,
        ]

    out += [
        "",
        "## Where the ledger says we are (`docs/PROGRESS.md`, verbatim)",
        "",
        ledger_row(),
        "",
        "## Read in full when the task needs them — never projected, never compressed",
        "",
        "| Section | Command |",
        "| --- | --- |",
    ]
    out += [
        f"| {label} | `sed -n {rng} docs/00_MASTER_PLAN.md` |" for label, rng in FULL_TEXT_ON_DEMAND
    ]
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    if len(argv) != 1 or not argv[0].lstrip("-").isdigit():
        print("usage: ./m brief <day>", file=sys.stderr)
        return 1
    print(build(int(argv[0])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
